### ISSUE TITLE
关键字定位问题，感觉只匹配了Y坐标，X坐标都是在右边

### ISSUE THREAD

**Issue by lemsn** [dushitaoyuan/little-pdf#3]
请问这个问题，如何修正呢？

![图片](https://user-images.githubusercontent.com/9290824/142560619-639b9082-b900-4378-8615-752bfb0c0bde.png)

**Comment by dushitaoyuan** [comment]
可以修改定位的部分代码，关键词定位测试样本较少，测试数据多以右侧为主，代码中部分定位代码，位置修正以[右上角坐标](https://github.com/dushitaoyuan/little-pdf/blob/master/little-pdf-core/src/main/java/com/taoyuanx/littlepdf/sign/Itext5PdfSign.java)为准

建议关键词部分有标识突出，方便定位
